rackerlabs/docs-cloud-identity

- api-docs/api-operations/methods/roles/get-list-global-roles-assigned-to-a-user-v2.0.rst
> Change get user by ID reference to list users

- api-docs/quickstart-guide.rst
Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.
Integrate edits from how-to article https://support.rackspace.com/how-to/introduction-to-encrypted-authenticated-tokens/
> Incorporate editor updates

- api-docs/authentication-info/mfa-content/proc-mfa-setup-otp.rst
- api-docs/conf.py
Change won't take affect until the content is pushed to production.
> Disable Spinx permalink formatting

- api-docs/authentication-info/mfa-content/proc-mfa-setup-otp.rst
- api-docs/conf.py
Reverts rackerlabs/docs-cloud-identity#43
> Revert "Disable Spinx permalink formatting"

- api-docs/authentication-info/mfa-content/proc-mfa-setup-otp.rst
> Fix info about auth token re-issue

- api-docs/api-reference/methods/users/post-forgot-pwd-v2.0.rst
- api-docs/api-reference/methods/users/post-reset-pwd-v2.0.rst
- api-docs/api-reference/users-operations.rst
> Add documentation on forgot password flow.

- api-docs/api-reference/secret-answer-operations.rst
- api-docs/api-reference/tenant-operations.rst
- api-docs/api-reference/token-operations.rst
- api-docs/api-reference/users-operations.rst
- api-docs/common-gs/how-to-use-curl.rst
- tox.ini
Note: This change also modifies the tox.ini file in order to run all check on `tox` run.
> Fix syntax issues

- api-docs/api-reference/domain-operations.rst
- api-docs/api-reference/methods/domains/get-get-a-domain-v2.0-rax-auth-domains-domainid.rst
- api-docs/api-reference/methods/domains/get-list-domains-v2.0-rax-auth-domains.rst
- api-docs/api-reference/methods/domains/put-update-a-domain.rst
- tox.ini
> [CID-750] - Allow updating/retrieving sessionTimeout attribute on domain

- .gitignore
- api-docs/general-api-info/authentication-info/authentication-ref/user-response-object.rst
- api-docs/general-api-info/authentication-info/sample-auth-req-response.rst
> CID-753 - Docs update for session inactivity timeout on auth calls

- api-docs/api-reference/methods/domains/get-get-a-domain-v2.0-rax-auth-domains-domainid.rst
- api-docs/api-reference/methods/domains/get-list-domains-v2.0-rax-auth-domains.rst
> [CID-761] - Allow retrieving rcn attribute on domain

- api-docs/api-reference/methods/domains/get-get-a-domain-v2.0-rax-auth-domains-domainid.rst
- api-docs/api-reference/methods/domains/get-list-domains-v2.0-rax-auth-domains.rst
- api-docs/api-reference/methods/users/get-accessible-domains-for-user-v2.0.rst
- api-docs/api-reference/users-operations.rst
> [CID-763] - Update Get Accessible Domains/Get Accessible Domains for User to return rcn attribute

- .gitignore
- api-docs/api-reference/domain-operations.rst
- api-docs/api-reference/methods/domains/get-get-a-domain-v2.0-rax-auth-domains-domainid.rst
- api-docs/api-reference/methods/domains/get-list-domains-v2.0-rax-auth-domains.rst
- api-docs/api-reference/methods/domains/put-update-a-domain.rst
- api-docs/general-api-info/authentication-info/authentication-ref/user-response-object.rst
- api-docs/general-api-info/authentication-info/sample-auth-req-response.rst
- tox.ini
> [Housekeeping] - Merge 3.11.0 into master

- api-docs/api-reference/methods/tenants/get-list-tenants-v2.0.rst
- api-docs/spelling_wordlist.txt
> [CID-486] - Add ?apply_rcn_roles support to v2.0 List Tenants

- api-docs/api-reference/methods/token/post-authenticate-as-tenant-with-token-v2.0-tokens.rst
- api-docs/api-reference/methods/token/post-authenticate-as-user-with-password-or-api-key-v2.0-tokens.rst
- api-docs/api-reference/methods/token/post-authenticate-with-multi-factor-authentication-passcode-credentials-v2.0-tokens.rst
- api-docs/spelling_wordlist.txt
> [CID-861] - Updating auth documentation for RCN roles

- api-docs/api-reference/domain-operations.rst
- api-docs/api-reference/methods/domains/get-password-policy-on-domain-v2.0.rst
- api-docs/api-reference/methods/domains/set-password-policy-on-domain-v2.0.rst
- api-docs/api-reference/methods/users/change-pwd-v2.0.rst
- api-docs/api-reference/users-operations.rst
- api-docs/spelling_wordlist.txt
> [CID-877] - Adding documentation for password policies

- api-docs/api-reference/methods/token/get-validate-token-v2.0-tokens-tokenid.rst
> [CID-865] - Updating validate docs per RCN roles

- api-docs/api-reference/methods/users/delete-user-api-key-credentials-v2.0-users-userid-os-ksadm-credentials-rax-kskey.rst
> [housekeeping] - Fix minor syntax issues

- api-docs/api-reference/methods/users/delete-user-api-key-credentials-v2.0-users-userid-os-ksadm-credentials-rax-kskey.rst
- api-docs/spelling_wordlist.txt
> Rebase master into 3.12.0

- api-docs/api-reference/identity-provider-operations.rst
- api-docs/api-reference/index.rst
- api-docs/api-reference/methods/identity-provider/post-create-identity-provider-with-metadata-v2.0.rst
> [CID-883] - Modify 'Create IDP' to support metadata.xml

- api-docs/api-reference/identity-provider-operations.rst
- api-docs/api-reference/index.rst
- api-docs/api-reference/methods/identity-provider/get-identity-provider-metadata-v2.0.rst
- api-docs/api-reference/methods/identity-provider/post-create-identity-provider-with-metadata-v2.0.rst
> [CID-885] - Get IDPs current metadata.xml

- api-docs/api-reference/identity-provider-operations.rst
- api-docs/api-reference/methods/identity-provider/put-update-identity-provider-with-metadata-v2.0.rst
- api-docs/spelling_wordlist.txt
> [CID-932] - Update DOMAIN IDP via metadata.xml

- api-docs/api-reference/identity-provider-operations.rst
- api-docs/api-reference/index.rst
- api-docs/api-reference/methods/identity-provider/get-identity-provider-metadata-v2.0.rst
- api-docs/api-reference/methods/identity-provider/post-create-identity-provider-with-metadata-v2.0.rst
- api-docs/api-reference/methods/identity-provider/put-update-identity-provider-with-metadata-v2.0.rst
- api-docs/spelling_wordlist.txt
> [Housekeeping] - Merge 3.13.0 into master

- api-docs/api-reference/identity-provider-operations.rst
- api-docs/api-reference/methods/identity-provider/get-identity-provider-v2.0.rst
- api-docs/api-reference/methods/identity-provider/get-list-identity-providers-v2.0.rst
- api-docs/spelling_wordlist.txt
> [CID-943] - Allow external users to get/list IDPs

- api-docs/api-reference/identity-provider-operations.rst
- api-docs/api-reference/methods/identity-provider/get-identity-provider-mapping-policy-v2.0.rst
- api-docs/api-reference/methods/identity-provider/put-update-identity-provider-mapping-policy-v2.0.rst
> [CID-1000] - Accept YAML attribute mapping policies

- api-docs/api-reference/identity-provider-operations.rst
- api-docs/api-reference/methods/token/get-list-endpoints-for-token-v2.0-tokens-tokenid.rst
> Fix minor issues in master

- api-docs/api-reference/methods/tenants/get-list-users-for-tenant-v2.0.rst
- api-docs/api-reference/tenant-operations.rst
> [CID-1272] - Find users by Contact ID

- api-docs/api-reference/identity-provider-operations.rst
- api-docs/api-reference/methods/identity-provider/put-update-identity-provider-v2.0.rst
- api-docs/api-reference/methods/tenants/get-list-users-for-tenant-v2.0.rst
- api-docs/api-reference/tenant-operations.rst
> Merge 3.18.0 into Master

- CONTRIBUTING.md
- README.md
- api-docs/additional-resources.rst
- api-docs/api-reference/extensions-operations.rst
- api-docs/api-reference/index.rst
- api-docs/api-reference/methods/extensions/get-list-extensions-v2.0.rst
- api-docs/api-reference/methods/users/post-forgot-pwd-v2.0.rst
- api-docs/api-reference/methods/versions/get-list-versions.rst
- api-docs/api-reference/token-operations.rst
- api-docs/common-gs/how-to-use-curl.rst
- api-docs/conf.py
- api-docs/general-api-info/service-access.rst
- api-docs/general-api-info/svc-catalog-ovw.rst
- api-docs/getting-started/authenticate.rst
- api-docs/getting-started/concepts.rst
- api-docs/getting-started/manage-auth-tokens.rst
- api-docs/getting-started/mfa-content/proc-mfa-enforce.rst
- api-docs/getting-started/mfa-content/proc-mfa-setup-phone.rst
- api-docs/index.rst
requested by the Identity dev team
> Change all occurrences of Rackspace Identity to Identity as

- api-docs/api-reference/methods/identity-provider/put-update-identity-provider-mapping-policy-v2.0.rst
- api-docs/api-reference/methods/phone-pin/reset-phone-pin.rst
- api-docs/api-reference/methods/phone-pin/unlock-phone-pin.rst
- api-docs/api-reference/methods/token/get-validate-token-v2.0-tokens-tokenid.rst
- api-docs/api-reference/methods/token/post-authenticate-as-tenant-with-token-v2.0-tokens.rst
- api-docs/api-reference/methods/users/get-list-users-v2.0.rst
- api-docs/api-reference/methods/users/get-user-by-id-v2.0.rst
- api-docs/api-reference/methods/users/post-user-information-and-password-v2.0.rst
- api-docs/api-reference/phone-pin-operations.rst
- api-docs/getting-started/mfa-content/proc-mfa-setup-otp.rst
to have sections with links to different types of operations
> Change phone PIN to Support PIN and fix phone-pin-operations.rst

- api-docs/api-reference/methods/roles/get-list-users-with-role-v2.0.rst
- api-docs/api-reference/methods/users/post-user-information-and-password-v2.0.rst
- api-docs/api-reference/role-operations.rst
- Create documentation for List Users with Role API call
- correcting api-docs/api-reference/methods/users/post-user-information-and-password-v2.0.rst
> CID-2466-Documentation for List Users with Role API call

- api-docs/_templates/scripts.html
@ssalinas24 
url link: https://developer.rackspace.com/docs/cloud-identity/v2/ maps correctly to readme.io: https://docs.rackspace.com/docs/cloud-identity-v2-getting-started
The content is migrated to Readme.io.
Could you please review and merge the PR.
> Replaced: Polyfill
